version: 1
build:
  main: cmd/kyved
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: dummy
    mnemonic: expect crisp umbrella hospital firm exhibit future size slot update blood
      deliver fat happy ghost visa recall usual path purity junior ring ordinary stove
  - name: alice
    coins:
      - 2000000000000000tkyve
    mnemonic: worry grief loyal smoke pencil arrow trap focus high pioneer tomato hedgehog
      essence purchase dove pond knee custom phone gentle sunset addict mother fabric
  - name: bob
    coins:
      - 1000000000000000tkyve
    mnemonic: crash sick toilet stumble join cash erode glory door weird diagram away
      lizard solid segment apple urge joy annual able tank define candy demise
  - name: charlie
    coins:
      - 1000000000000000tkyve
    mnemonic: shoot inject fragile width trend satisfy army enact volcano crowd message
      strike true divorce search rich office shoulder sport relax rhythm symbol gadget
      size
  - name: faucet
    coins:
      - 1000000000000000tkyve
    mnemonic: open home share route party lake room solution quantum pact model avocado
      humor dilemma review desert turtle total humor produce rate keen eagle fee
  - name: foundation
    coins:
      # for fees
      - 1000000tkyve
    #    address: kyve1fd4qu868n7arav8vteghcppxxa0p2vna5f5ep8
    mnemonic: evidence taxi material cabin annual phrase practice unhappy safe jealous
      section drink illness panther bread aim mouse dolphin deliver ready doll finger search cheap
  - name: foundation_inflation
    coins:
      # for fees
      - 1000000tkyve
    #    address: kyve1tuxsc7ez79aydyee86qxm05zyx0l7d78c2zzsn
    mnemonic: hold urge sustain chef furnace foam oven fall harsh core anchor during crew secret
      craft rhythm choose gold soft aisle sort phrase enter orphan
faucet:
  name: faucet
  coins:
    - 1000000000000tkyve
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/swagger/swagger.yml
genesis:
  app_state:
    bank:
      balances:
        - address: "kyve1e29j95xmsw3zmvtrk4st8e89z5n72v7nf70ma4"  # team module
          coins:
            - denom: "tkyve"
              amount: "165000000000000000"
        - address: "kyve1vg5325u5mat0y44g73n8t8z2le26fsa4n947f5"  # funders module
          coins:
            - denom: "tkyve"
              amount: "5300000000000000"
      supply:
        - denom: "tkyve"
          amount: "170300000000000000"  # all balances together
    delegation:
      params:
        unbonding_delegation_time: 10
    global:
      params:
        burn_ratio: "0.5"
        min_gas_price: "1"
    gov:
      params:
        max_deposit_period: 300s
        min_deposit:
          - amount: "50_000_000_000"
            denom: tkyve
        voting_period: 20s
        quorum: "0.001"
    mint:
      params:
        mint_denom: "tkyve"
    team:
      account_count: "8"
      account_list:
        - id: "0"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1686693600"
          commencement: "1663106400"
        - id: "1"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1749852000"
          commencement: "1694642400"
        - id: "2"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1694642400"
          commencement: "1615676400"
        - id: "3"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1702508400"
          commencement: "1647212400"
        - id: "4"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1741906800"
          commencement: "1663106400"
        - id: "5"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1804978800"
          commencement: "1710370800"
        - id: "6"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1741906800"
          commencement: "1615676400"
        - id: "7"
          total_allocation: "1000000000000"
          unlocked_claimed: "0"
          clawback: "1804978800"
          commencement: "1647212400"
    pool:
      params:
        protocol_inflation_share: "0.04"
      pool_count: "2"
      pool_list:
        - config: "{\"network\":\"kyve-1\",\"rpc\":\"https://rpc-eu-1.kyve.network\"}"
          current_compression_id: "1"
          current_index: "0"
          current_key: ""
          current_storage_provider_id: "1"
          current_summary: ""
          id: "0"
          logo: ""
          max_bundle_size: "100"
          min_delegation: "100000000000"
          name: "KYVE // Mainnet"
          inflation_share_weight: "2500000000"
          disabled: false
          runtime: '@kyvejs/tendermint-bsync'
          start_key: "1"
          total_bundles: "0"
          upload_interval: "60"
          protocol:
            version: "1.0.0"
            binaries: "{\"kyve-linux-arm64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-linux-arm64.zip\",\"kyve-linux-x64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-linux-x64.zip\",\"kyve-macos-x64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-macos-x64.zip\"}"
            last_upgrade: "0"
          upgrade_plan:
            version: ""
            binaries: ""
            scheduled_at: "0"
            duration: "0"
        - config: "{\"network\":\"kyve-1\",\"rpc\":\"https://rpc-eu-1.kyve.network\"}"
          current_compression_id: "1"
          current_index: "0"
          current_key: ""
          current_storage_provider_id: "1"
          current_summary: ""
          id: "1"
          logo: ""
          max_bundle_size: "100"
          min_delegation: "100000000000"
          name: "KYVE // Blub"
          inflation_share_weight: "2500000000"
          disabled: false
          runtime: '@kyvejs/tendermint-bsync'
          start_key: "1"
          total_bundles: "0"
          upload_interval: "60"
          protocol:
            version: "1.0.0"
            binaries: "{\"kyve-linux-arm64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-linux-arm64.zip\",\"kyve-linux-x64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-linux-x64.zip\",\"kyve-macos-x64\":\"https://github.com/KYVENetwork/kyvejs/releases/download/%40kyvejs%2Ftendermint-bsync%401.0.0/kyve-macos-x64.zip\"}"
            last_upgrade: "0"
          upgrade_plan:
            version: ""
            binaries: ""
            scheduled_at: "0"
            duration: "0"
    stakers:
      params:
        commission_change_time: 10
    staking:
      params:
        bond_denom: tkyve
    funders:
      params:
        min_funding_amount: 1000000000
        min_funding_amount_per_bundle: 10000000
      funder_list:
        - address: "kyve1jq304cthpx0lwhpqzrdjrcza559ukyy3zsl2vd"
          contact: "https://twitter.com/kyvenetwork"
          moniker: "Alice"
          description: "Alice is the first funder of the KYVE network."
          website: "https://kyve.network"
          identity: "0657A086E5201562"
        - address: "kyve1ze3ncmkvat3t2mcj9e3uy8uktat4fq2vltcnat"
          contact: "https://twitter.com/kyvenetwork"
          moniker: "Otto"
          description: "Another funder of the KYVE network."
          website: "https://ot.to"
          identity: "0657A086E5201562"
      funding_list:
        - pool_id: 0
          funder_address: "kyve1jq304cthpx0lwhpqzrdjrcza559ukyy3zsl2vd"
          amount: 5000000000000
          amount_per_bundle: 230000000
          total_funded: 2200400000000
        - pool_id: 0
          funder_address: "kyve1ze3ncmkvat3t2mcj9e3uy8uktat4fq2vltcnat"
          amount: 200000000000
          amount_per_bundle: 20000000
          total_funded: 64500000000
        - pool_id: 1
          funder_address: "kyve1ze3ncmkvat3t2mcj9e3uy8uktat4fq2vltcnat"
          amount: 100000000000
          amount_per_bundle: 10000000
          total_funded: 23000000000
      funding_state_list:
        - pool_id: 0
          active_funder_addresses: [ "kyve1jq304cthpx0lwhpqzrdjrcza559ukyy3zsl2vd", "kyve1ze3ncmkvat3t2mcj9e3uy8uktat4fq2vltcnat" ]
        - pool_id: 1
          active_funder_addresses: [ "kyve1ze3ncmkvat3t2mcj9e3uy8uktat4fq2vltcnat" ]
  chain_id: kyve-local
validators:
  - name: alice
    bonded: 1000000000000tkyve
    config:
      consensus:
        timeout_commit: "2s"
        timeout_propose: "2s"