name: test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Check out repository code
        uses: actions/checkout@v4
      # Setup Golang
      - name: 🐿 Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      # Test & coverage report creation
      - name: Test & coverage report creation
        run: go test -cover -mod=readonly ./x/...